VictoryRoad_1F_YouHaveFoughtWellText::
	.string "You have fought well.$"

VictoryRoad_1F_DoYouWishToChallengeMeText::
	.string "Do you wish to challenge me?$"

VictoryRoad_1F_BeatOtherMembersFirstText::
	.string "You have to beat the other\n"
	.string "members before facing me.$"

VictoryRoad_1F_GuardianFireText::
	.string "I am MICHAEL of FIRE.\n"
	.string "I have mastered to control fire\l"
	.string "and I achieved to become one of the\l"
	.string "ELITE 17!$"


VictoryRoad_1F_GuardianSteelText::
	.string "I am JUDE of STEEL.\n"
	.string "Nothing is tougher than steel!\l"
	.string "You’ll get a hard time beating me!$"

VictoryRoad_1F_GuardianDarknessText::
	.string "I am ELLAINE of DARKNESS.\n"
	.string "Creatures of the dark are not only\l"
	.string "frightening, but they are also strong!$"

VictoryRoad_1F_GuardianNormalText::
	.string "I am MATTHEW of NORMAL-types.\n"
	.string "I specialize on ordinary NORMAL types,\l"
	.string "but do not underestimate us!$"

VictoryRoad_1F_GuardianFightingText::
	.string "I am ALEXIS of FIGHTING.\n"
	.string "Each strike of our punches can\l"
	.string "shake the earth! Hah!$"

VictoryRoad_1F_GuardianFlyingText::
	.string "I am ADALENE of FLYING-types!\n"
	.string "Oh, these wings, we can achieve\l"
	.string "freedom to our hearts and souls.$"

VictoryRoad_1F_GuardianPoisonText::
	.string "I am STEVEN of POISON-types.\n"
	.string "How horrible it is to be poisoned\l"
	.string "by powerful venom.$"

VictoryRoad_1F_GuardianGhostText::
	.string "I am JENNY of GHOST-types.\n"
	.string "The spirits of this world hold many\l"
	.string "secrets and hidden potentials.$"

VictoryRoad_1F_GuardianBugText::
	.string "I am DAVID of BUG-types.\n"
	.string "Some say they’re cute, and some\l"
	.string "think they’re scary, but really,\l"
	.string "they’re stronger than they look.$"

VictoryRoad_1F_GuardianRockText::
	.string "I am BRANDON of ROCK-types.\n"
	.string "Rocks are stronger than ground...$"

VictoryRoad_1F_GuardianGroundText::
	.string "I am GRACE of GROUND-types.\n"
	.string "The sands of nature hold power.$"

VictoryRoad_1F_GuardianIceText::
	.string "I am AURORA of ICE.\n"
	.string "I can promise to bring you a\l"
	.string "winter-cold battle! Too cold for you\l"
	.string "to handle!$"

VictoryRoad_1F_GuardianPsychicText::
	.string "I am ALLEN of PSYCHIC.\n"
	.string "I can read your moves before you\l"
	.string "even give commands to your POKéMON!$"

VictoryRoad_1F_GuardianGrassText::
	.string "I am MARY JOY of GRASS.\n"
	.string "Nature has given us many blessings,\l"
	.string "but be cautious, for it also hides\l"
	.string "incredible power!$"

VictoryRoad_1F_GuardianElectricText::
	.string "I am LOUIS of ELECTRICITY.\n"
	.string "One zap and it’s over.$"

VictoryRoad_1F_GuardianWaterText::
	.string "I am ELLIONORE of WATER.\n"
	.string "Water is a very unpredictable type,\l"
	.string "so watch out!\p"
	.string "Mastering it was not easy.$"

VictoryRoad_1F_GuardianDragonText::
	.string "I am WALTER of DRAGONS.\n"
	.string "These mythical creatures hold amazing\l"
	.string "powers capable of bringing down\l"
	.string "almost any opponents!$"

VictoryRoad_1F_BattleWasSuperbReadyToFaceChampionText::
	.string "That battle was superb!\n"
	.string "And now, you are ready to face\l"
	.string "the champion!\p"
	.string "Before that, let me heal your team.$"

VictoryRoad_1F_AndNowFaceChallengeThatAwaitsYouText::
	.string "And now, face the challenge that\n"
	.string "awaits you!$"

VictoryRoad_1F_TheChampionAwaitsText::
	.string "The champion awaits...!$"

VictoryRoad_1F_HealThreeTimesText::
	.string "I am only allowed to heal your\n"
	.string "POKéMON for three times.\p"
	.string "Do you want me to heal them?$"

VictoryRoad_1F_HealTwoTimesText::
	.string "I am only allowed to heal your\n"
	.string "POKéMON for two more times.\p"
	.string "Do you want me to heal them?$"

VictoryRoad_1F_HealOneTimeText::
	.string "I am only allowed to heal your\n"
	.string "POKéMON once more.\p"
	.string "Do you want me to heal them?$"

VictoryRoad_1F_NurseJoy_ISeeWishGoodLuckText::
	.string "I see.\n"
	.string "Then I wish you good luck!$"

VictoryRoad_1F_PokemonFullyHealedGoodLuckText::
	.string "Your POKéMON have been fully healed.\n"
	.string "Good luck with your battles!$"

VictoryRoad_1F_IApologizeNoLongerAllowedToHealText::
	.string "I apologize, but I am no longer\n"
	.string "allowed to heal your POKéMON.$"
