VictoryRoad_1F_YouHaveFoughtWellText::
	.string "You have fought well.$"

VictoryRoad_1F_DoYouWishToChallengeMeText::
	.string "Do you wish to challenge me?$"

VictoryRoad_1F_BeatOtherMembersFirstText::
	.string "You have to beat the other\n"
	.string "members before facing me.$"

VictoryRoad_1F_GuardianFireText::
	.string "FIRE$"
/*
	.string "I am MICHAEL of FIRE.\n"
	.string "I have mastered to control fire\l"
	.string "and I achieved to become one of the\l"
	.string "ELITE 17!$"
*/

VictoryRoad_1F_GuardianSteelText::
	.string "STEEL$"

VictoryRoad_1F_GuardianDarknessText::
	.string "DARK$"

VictoryRoad_1F_GuardianNormalText::
	.string "NORMAL$"

VictoryRoad_1F_GuardianFightingText::
	.string "FIGHTING$"

VictoryRoad_1F_GuardianFlyingText::
	.string "FLYING$"

VictoryRoad_1F_GuardianPoisonText::
	.string "POISON$"

VictoryRoad_1F_GuardianGhostText::
	.string "GHOST$"

VictoryRoad_1F_GuardianBugText::
	.string "BUG$"

VictoryRoad_1F_GuardianRockText::
	.string "ROCK$"

VictoryRoad_1F_GuardianGroundText::
	.string "GROUND$"

VictoryRoad_1F_GuardianIceText::
	.string "ICE$"

VictoryRoad_1F_GuardianPsychicText::
	.string "PSYCHIC$"

VictoryRoad_1F_GuardianGrassText::
	.string "GRASS$"

VictoryRoad_1F_GuardianElectricText::
	.string "ELECTRIC$"

VictoryRoad_1F_GuardianWaterText::
	.string "WATER$"

VictoryRoad_1F_GuardianDragonText::
	.string "DRAGON$"

VictoryRoad_1F_BattleWasSuperbReadyToFaceChampionText::
	.string "That battle was superb!\n"
	.string "And now, you are ready to face\l"
	.string "the champion!\p"
	.string "Before that, let me heal your team.$"

VictoryRoad_1F_AndNowFaceChallengeThatAwaitsYouText::
	.string "And now, face the challenge that\n"
	.string "awaits you!$"

VictoryRoad_1F_TheChampionAwaitsText::
	.string "The champion awaits...!$"

VictoryRoad_1F_HealThreeTimesText::
	.string "I am only allowed to heal your\n"
	.string "POKéMON for three times.\p"
	.string "Do you want me to heal them?$"

VictoryRoad_1F_HealTwoTimesText::
	.string "I am only allowed to heal your\n"
	.string "POKéMON for two more times.\p"
	.string "Do you want me to heal them?$"

VictoryRoad_1F_HealOneTimeText::
	.string "I am only allowed to heal your\n"
	.string "POKéMON once more.\p"
	.string "Do you want me to heal them?$"

VictoryRoad_1F_NurseJoy_ISeeWishGoodLuckText::
	.string "I see.\n"
	.string "Then I wish you good luck!$"

VictoryRoad_1F_PokemonFullyHealedGoodLuckText::
	.string "Your POKéMON have been fully healed.\n"
	.string "Good luck with your battles!$"

VictoryRoad_1F_IApologizeNoLongerAllowedToHealText::
	.string "I apologize, but I am no longer\n"
	.string "allowed to heal your POKéMON.$"
