gBirchSpeech_Welcome:: @ 81C6D78
	.string "TODO$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "“TODO”$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "TODO${PAUSE_UNTIL_PRESS}"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "And you are?$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "All right.\n"
	.string "What’s your name?$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "So it’s {PLAYER}?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "Ah, okay!\p"
	.string "You’re {PLAYER}.\l"
	.string "I get it now!$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Just remember:\p"
	.string "Don’t build a team.$"
