gBirchSpeech_Welcome:: @ 81C6D78
	.string "Why, hello there!\n"
	.string "We’re so glad to have you\l"
	.string "participating in the ELITE 17\l"
	.string "challenge!\p"

	.string "The details of the challenge will be\n"
	.string "revealed later, but let us tell you\l"
	.string "about our company goal.\p"
	
	.string "Here at Solomeme Inc., we reject the\n"
	.string "idea that a team is necessary to\l"
	.string "win POKéMON battles.\p"
	
	.string "Instead, we focus on investing all\n"
	.string "our resources into one POKéMON.\p"
	
	.string "But how, you may ask, can one win\n"
	.string "battles with only one POKéMON\l"
	.string "against teams of six?{PAUSE_UNTIL_PRESS}$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "The answer:$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "Is items.\p"

	.string "Items are the bulk of the solomeme\n"
	.string "philosophy.\p"
	
	.string "HP healing items allow a POKéMON to\n"
	.string "take more hits than they normally\l"
	.string "would.\p"

	.string "Status healing items counteract\n"
	.string "annoying statuses that otherwise\l"
	.string "would have to be dealt with for\l"
	.string "the remainder of the battle.\p"

	.string "X Items are the most important out\n"
	.string "of all the items.\p"

	.string "They can raise the stats of a\n"
	.string "POKéMON to levels that allow it to\l"
	.string "win battles that they would\l"
	.string "normally not be able to win.\p"

	.string "Offensive X Items grant POKéMON the\n"
	.string "ability to require less hits to\l"
	.string "faint opposing POKéMON, and in\l"
	.string "turn allow the POKéMON to receive\l"
	.string "less hits and thus take less\l"
	.string "damage.\p"
	
	.string "Defensive X Items can be critical\n"
	.string "when setting up offensive X Items\l"
	.string "as they increase the amount of\l"
	.string "hits that a POKéMON can take.\p"
	
	.string "In conjunction with HP healing\n"
	.string "items, they can provide the turns\l"
	.string "necessary to set up for a sweep.\p"
	
	.string "Defensive X Items can also be used\n"
	.string "to enable a POKéMON to pull off a\l"
	.string "successful two-hit against an\l"
	.string "opposing POKéMON that would\l"
	.string "otherwise be deadly.\p"

	.string "X SPEED, while simple, has a critical\n"
	.string "role in preventing deadly opposing\l"
	.string "POKéMON from even landing an\l"
	.string "attack on your POKéMON.\p"

	.string "We also have utility X Items such as\n"
	.string "X ACCURACY, GUARD SPEC., and\l"
	.string "DIRE HIT.\p"
	
	.string "While these aren’t as crucial as the\n"
	.string "aforementioned X Items, they can\l"
	.string "be useful in certain situations.\p"
	
	.string "(Except DIRE HIT. DIRE HIT should\n"
	.string "not be seriously used.)\p"
	
	.string "X Items are so important that our\n"
	.string "top researchers have created\l"
	.string "double, or “2” variants of\l"
	.string "the stat boosting X Items.\p"

	.string "These variants will raise the\n"
	.string "relevant stat by two stages\l"
	.string "in a single turn.\p"
	
	.string "The drawback is that they cost\n"
	.string "three times as much as a regular\l"
	.string "X Item.\p"
	
	.string "And if you think encouraging the\n"
	.string "use of items will make battles too\l"
	.string "easy, then have no fear.\p"
	
	.string "We’ve solved that issue by increas-\n"
	.string "ing the price of items across the\l"
	.string "board.\p"
	
	.string "So you’ll have to choose wisely which\n"
	.string "items to bring against the ELITE\l"
	.string "17.\p"
	
	.string "But enough about solomeme.\n"
	.string "Why not tell us about yourself?{PAUSE_UNTIL_PRESS}$"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "And you are?$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "All right.\n"
	.string "What’s your name?$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "So it’s {PLAYER}?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "Ah, okay!\p"
	.string "You’re {PLAYER}.\l"
	.string "I get it now!$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "All right, are you ready?\n"
	.string "The ELITE 17 challenge is about to\l"
	.string "start.\p"
	.string "If you’re stuck, just remember our\n"
	.string "motto.\p"
	.string "“Why build a team,\n"
	.string "when you can solomeme?”\p"
	.string "Good luck!{PAUSE_UNTIL_PRESS}$"
