VictoryRoad_B1F_YikesText::
	.string "“Pokémon: Let’s Go, Pikachu!” and\n"
	.string "“Let’s Go, Eevee!” are upcoming\l"
	.string "role-playing video games (RPGs)\l"
	.string "developed by Game Freak and published\l"
	.string "by The Pokémon Company and Nintendo\l"
	.string "for the Nintendo Switch.\p"

	.string "The games are the first installments\n"
	.string "of the main Pokémon RPG series for\l"
	.string "the Nintendo Switch.\p"
	
	.string "They are enhanced remakes of the\n"
	.string "1998 video game Pokémon Yellow, they\l"
	.string "will also contain influences from\l"
	.string "Pokémon Go, as well as integration\l"
	.string "with Go, and will support a new optional\l"
	.string "controller called the Poké Ball Plus.\p"

	.string "The games are scheduled to be"
	.string "released worldwide on November 16, 2018.data/maps/VictoryRoad…B1F/text.inc:3: error: unknown character U+27$"
