EverGrandeCity_PokemonLeague_Text_191804:: @ 8191804
	.string "TRAINER! Believe in yourself and your\n"
	.string "POKéMON, and go forth!$"

EverGrandeCity_PokemonLeague_Text_19179C::
	.string "When you’re ready, just come back and\n"
	.string "tell us.$"

EverGrandeCity_PokemonLeague_PokemonShop_PartyFullText::
	.string "Sorry, your party is\n"
	.string "full.$"

EverGrandeCity_PokemonLeague_Text_WelcomeToElite17::
	.string "Welcome to the ELITE 17!\p"

	.string "Before I explain anything, please take\n"
	.string "these items as a commemorative gift.$"

EverGrandeCity_PokemonLeague_Text_NowThenWhatToExplain::
	.string "Now then, what do you need me to\n"
	.string "explain?$"

EverGrandeCity_PokemonLeague_Text_Elite17:: @ 81916FD
	.string "In this challenge, you will have to face\n"
	.string "17 ELITE TRAINERs mastered in each\l"
	.string "type, followed by a CHAMPION TRAINER.\p"

	.string "You are able to fight the trainers in\n"
	.string "any order, apart from the DRAGON\l"
	.string "TRAINER and the CHAMPION.\p"

	.string "The DRAGON TRAINER can only be fought\n"
	.string "after all other TRAINERs have been\l"
	.string "defeated, and has higher level POKéMON.\p"
	
	.string "The CHAMPION can only be fought after\n"
	.string "all ELITE 17 trainers have been\l"
	.string "defeated.\p"

	.string "The mode level of the ELITE 17 trainers\n"
	.string "except the DRAGON TRAINER is 85.\p"

	.string "You will be allowed three free heals in\n"
	.string "this challenge.\p"

	.string "You are allowed to leave at any time, but\n"
	.string "subsequent matches against trainers\l"
	.string "you have fought will have their\l"
	.string "experience points and money payout\l"
	.string "reduced.\p"
	
	.string "We encourage saving before fighting\n"
	.string "each ELITE 17 trainer.\p"

	.string "All three MARTs and the healer are\n"
	.string "available in the challenge as rocks\l"
	.string "in the center of the map.$"

EverGrandeCity_PokemonLeague_Text_NPCs::
	.string "To the top left is a NURSE to heal\n"
	.string "your POKéMON.\p"
	
	.string "To the bottom left is the MOVE DELETER,\n"
	.string "and to the bottom right is the MOVE\l"
	.string "TUTOR, who charges ¥5000 instead of a\l"
	.string "HEART SCALE.\p"

	.string "To the top right are three shops that\n"
	.string "sell resources vital to winning against\l"
	.string "the ELITE 17.\p"
	
	.string "The left POKéMART employee sells\n"
	.string "POKéMON.\p"
	
	.string "It sells the base forms of all POKéMON,\n"
	.string "except certain baby POKéMON, which\l"
	.string "their second stage is sold instead, and\l"
	.string "legendary POKéMON, which are not sold\l"
	.string "at all.\p"

	.string "Each POKéMON has a base price of\n"
	.string "¥10000, plus a variable price based on\l"
	.string "level.\p"

	.string "The variable price will usually be the\n"
	.string "total experience of the POKéMON at\l"
	.string "that level, but there are some\l"
	.string "exceptions.\p"

	.string "POKéMON with the ERRATIC growth rate\n"
	.string "have their variable price set as if they\l"
	.string "had the SLOW growth rate, while\l"
	.string "POKéMON with the FLUCTUATING growth\l"
	.string "rate have their variable price as a\l"
	.string "POKéMON with the FAST growth rate.\p"
	
	.string "Pseudo-legendaries cost the price of a\n"
	.string "FLUCTUATING POKéMON.\p"
	
	.string "The middle POKéMART employee sells\n"
	.string "general items except TMs.\p"
	
	.string "The mart inventory is split up into the\n"
	.string "following sections:\p"
	
	.string "Healing items.\l"
	.string "X Items.\l"
	.string "Berries.\l"
	.string "Evolution Stones.\l"
	.string "WHITE HERB and MENTAL HERB.\l"
	.string "CHOICE BAND and LEFTOVERS.\l"
	.string "Type-boosting held items.\l"
	.string "Gimmick held items.\p"
	.string "POKéMON evolution held items and\n"
	.string "exclusive held items.\l"
	.string "Flutes.\l"
	.string "Vitamins.\p"

	.string "The right POKéMART employee sells every\n"
	.string "TM and HM.$"

EverGrandeCity_PokemonLeague_Text_EvolutionChanges::
	.string "We have also added new evolution items.\p"

	.string "LEVEL STONE evolves POKéMON which\n"
	.string "evolve by levelling up, which also\l"
	.string "includes evolutions such as\l"
	.string "happiness evolutions.\p"

	.string "TRADE STONE evolves POKéMON which\n"
	.string "evolve by trading.\p"

	.string "Also, the following methods are available\n"
	.string "to obtain certain POKéMON.\p"

	.string "For happiness evolutions, you can\n"
	.string "obtain max happiness by using a STAT\l"
	.string "vitamin. Note that this new effect of\l"
	.string "STAT vitamins applies to any POKéMON.\p"

	.string "For UMBREON and ESPEON, the POKé BALL\n"
	.string "on the POKé MART counter acts as a\l"
	.string "clock to change the time.\p"

	.string "FEEBAS now evolves using a TRADE STONE\n"
	.string "and a PRISM SCALE.$"

EverGrandeCity_PokemonLeague_Text_PPChanges::
	.string "Any boosting move which raises two\n"
	.string "offensive stats or one offensive and\l"
	.string "one other stat has been reduced to\l"
	.string "10 PP.\p"
	
	.string "Any boosting move which raises two\n"
	.string "defensive stats has been reduced to\l"
	.string "15 PP.\p"
	
	.string "Any boosting move which raises one\n"
	.string "offensive stat has been reduced to\l"
	.string "15 PP.\p"
	
	.string "Any boosting move which raises one\n"
	.string "defensive stat has been reduced to\l"
	.string "20 PP.\p"
	
	.string "Moves which only boost speed have not\n"
	.string "been affected.\p"

	.string "RETURN also has been reduced to 10 PP.$"
