EverGrandeCity_PokemonLeague_Text_1916FD:: @ 81916FD
	.string "In this challenge, you will have to face\n"
	.string "17 ELITE TRAINERs mastered in each\l"
	.string "type.\p"
	.string "You will be allowed three free heals in\n"
	.string "this challenge.\p"
	.string "You are allowed to leave at any time, but\n"
	.string "subsequent matches against trainers\l"
	.string "you have fought will have their\l"
	.string "experience points reduced.\p"
	.string "Are you ready?$"

EverGrandeCity_PokemonLeague_Text_191804:: @ 8191804
	.string "TRAINER! Believe in yourself and your\n"
	.string "POKéMON, and go forth!$"

EverGrandeCity_PokemonLeague_Text_19179C::
	.string "When you’re ready, just come back and\n"
	.string "tell us.$"

EverGrandeCity_PokemonLeague_PokemonShop_PartyFullText::
	.string "Sorry, your party is\n"
	.string "full.$"
