EverGrandeCity_PokemonLeague_Text_1916FD:: @ 81916FD
	.string "In this challenge, you will have to face\n"
	.string "a TRAINER mastered in each type, 17\l"
	.string "in total.\p"
	.string "You will be allowed three free heals in\n"
	.string "this challenge.\p"
	.string "Are you ready?$"

EverGrandeCity_PokemonLeague_Text_191804:: @ 8191804
	.string "TRAINER! Believe in yourself and your\n"
	.string "POKéMON, and go forth!$"

EverGrandeCity_PokemonLeague_Text_19179C::
	.string "When you’re ready, just come back and\n"
	.string "tell us.$"

EverGrandeCity_PokemonLeague_PokemonShop_PartyFullText::
	.string "Sorry, your party is\n"
	.string "full.$"
