FallarborTown_House2_Text_177AF4:: @ 8177AF4
	.string "I’m the MOVE TUTOR.\p"
	.string "I know all the moves that POKéMON\n"
	.string "learn - every one of them - and I can\l"
	.string "teach POKéMON those moves.\p"
	.string "I can teach a move to a POKéMON\n"
	.string "of yours if you’d like.\l"
	.string "I’ll do it for ¥5000.$"

FallarborTown_House2_Text_177BDB:: @ 8177BDB
	.string "Would you like me to teach a move\n"
	.string "to one of your POKéMON?$"

FallarborTown_House2_Text_177C3F:: @ 8177C3F
	.string "Which POKéMON needs tutoring?$"

FallarborTown_House2_Text_177C5D:: @ 8177C5D
	.string "Which move should I teach?$"

FallarborTown_House2_Text_177C78:: @ 8177C78
	.string "Sorry...\p"
	.string "It doesn’t appear as if I have any move\n"
	.string "I can teach that POKéMON.$"

FallarborTown_House2_Text_177CC3:: @ 8177CC3
	.string "{PLAYER} paid ¥5000 in exchange.$"

FallarborTown_House2_Text_177CEF:: @ 8177CEF
	.string "If your POKéMON need to learn a move,\n"
	.string "come back with ¥5000.$"

FallarborTown_House2_Text_177D33:: @ 8177D33
	.string "Hunh? There isn’t a single move that\n"
	.string "I can teach an EGG.$"
