#ifndef GUARD_BATTLE_AI_SWITCH_ITEMS_H
#define GUARD_BATTLE_AI_SWITCH_ITEMS_H

u8 GetMostSuitableMonToSwitchInto(void);

enum {
    AI_SWITCH_CANT_DO_FULL_HP_CANT_OUTSPEED,
    AI_SWITCH_CANT_DO_FULL_HP_CAN_OUTSPEED,
    AI_SWITCH_CAN_DO_FULL_HP_CANT_OUTSPEED,
    AI_SWITCH_CAN_DO_FULL_HP_CAN_OUTSPEED,
};

enum {
    AI_SWITCHSCORE_DONT_SWITCH_1,
    AI_SWITCHSCORE_DONT_SWITCH_2,
    AI_SWITCHSCORE_DO_SWITCH_3,
    AI_SWITCHSCORE_DO_SWITCH_4,
    AI_SWITCHSCORE_DONT_SWITCH_5,
    AI_SWITCHSCORE_DONT_SWITCH_6,
    AI_SWITCHSCORE_DO_SWITCH_7,
    AI_SWITCHSCORE_DO_SWITCH_8,
    AI_SWITCHSCORE_DONT_SWITCH_CAN_KO_9,
    AI_SWITCHSCORE_DONT_SWITCH_CAN_KO_10,
    AI_SWITCHSCORE_DONT_SWITCH_DEFAULT,
    AI_SWITCHSCORE_DONT_SWITCH_BAD,
    AI_SWITCHSCORE_DONT_SWITCH_IMPOSSIBLE,
};

extern struct BattlePokemon gAISwitchTempBattlePokemon;
extern u16 gCurrentMove;

#endif
