Text_LittlerootTown_StartHacking::
	.string "Start hacking!$"

LittlerootTown_Sign_PartyFullText::
	.string "Sorry, your party is\n"
	.string "full.$"

InstantTextTestText::
	.string "I see!\p"
	.string "So that’s how you imagine the concept\n"
	.string "of “Something” to be.\p"
	.string "Thank you!\n"
	.string "You’ve given me some good ideas.\p"
	.string "I think I can write a good story on\n"
	.string "POKéMON CONTESTS now.\p"
	.string "Maybe, just maybe, this story will even\n"
	.string "make it to television.\l"
	.string "I hope you’ll look forward to it!\p"
	.string "I see!\l"
	.string "So that’s how you imagine the concept\l"
	.string "of “Something” to be.\l"
	.string "Thank you!\l"
	.string "You’ve given me some good ideas.\l"
	.string "I think I can write a good story on\l"
	.string "POKéMON CONTESTS now.\l"
	.string "Maybe, just maybe, this story will even\l"
	.string "make it to television.\l"
	.string "I hope you’ll look forward to it!$"